### ISSUE TITLE
0.7.1: backup fails on numeric story IDs (file.replaceAll is not a function)

### ISSUE THREAD

**Issue by letphilipp** [webflorist/storyblok-backup#12]
Hey, after upgrading to 0.7.1, backups fail when fetching stories.

writeJson('stories', story.id, ...) passes a number as file, but the new filename sanitization calls file.replaceAll() without converting it to a string.
We did log it immediately before sanitization:

`{"folder":"stories","file":291107303821404,"type":"number"} `

Tested with Node.js 20.20.2 in Bitbucket Pipelines and 24.13.0 locally.

**possible fix**: convert file with String(file) before applying the existing sanitization.

**Comment by codeflorist** [comment]
@letphilipp Ah, sorry about that and many thanks for the report! i've just published v0.7.2 with a fix.
